###
avatar: 
favicon: 
#自动生成的摘要长度 建议文章中手动使用 <!--more--> 效果更佳
excerpt_length: 300
# 页面    
page:
  tag_count: true

# 主题颜色
theme_color:
  primary: blue-grey 
  accent: blue

# 搜索
search:
  local: true
  path: /search.xml
  placeholder: 请输入关键字

# 不蒜子计数
busuanzi:
  site: false
  page: false
  busuanzi_js: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# 文末结束语
passage_end_tag:
  enabled: false
  text: --- 本文结束 <i class="fa fa-heartbeat"></i> The End ---

# Google Adsense广告代码
google_adsense:
  enabled: false
  footer: ../_adsense/footer.ejs
  sidebar: ../_adsense/sidebar.ejs
  banner: ../_adsense/banner.ejs

# 数学公式渲染
math:
  enabled: false
  engine: mathjax ##可选渲染引擎：mathjax、katex
  mathjax:
    cdn: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  katex:
    cdn_css: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
    cdn_js: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js
    auto_render: https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js

# 菜单
menu:
  home: / || home
  #about: /about/ || user
  tags: /tags/ || bookmark
  categories: /categories/ || folder
  archives: /archives/ || archive
  sitemap: /sitemap.xml || map

# 页脚
footer:
  since: false
  powered: true
  theme: false
  beian:
    enable: false
    icp: false
  icon:
    # 图标名使用的是Font Awesome 5.11.2, 详见: https://fontawesome.com/
    enabled: false
    name: fas fa-heart
    color: "#d9333f"

# 评论
#comment:
  #use: gitalk
  ## Gitalk
  #gitalk_client_id: 
  #gitalk_client_secret: 
  #gitalk_repo: 
  #gitalk_owner: 
  #gitalk_sid_type:
  #gitalk_distractionFreeMode: true
  ## Disqus
  #disqus_shortname:
  ## Livere
  #livere_data_uid:
  ## Valine
  #valine_leancloud_app_id:
  #valine_leancloud_app_key:
  #valine_placeholder:
  #valine_page_size:
  #valine_avatar:
  #valine_lang:
  #valine_guest_info:
  #valine_notify:
  #valine_verify:
  ## 畅言
  #changyan_app_id:
  #changyan_app_key:
  #changyan_sid_type:

# 社交链接
#social:
  #E-Mail: mailto:kb1000fx@gmail.com || fas fa-envelope
  #GitHub: https://github.com/kb1000fx || fab fa-github
  #Steam: https://steamcommunity.com/profiles/76561198346798163 || fab fa-steam
  #Weibo: https://weibo.com/kb1000fx || fab fa-weibo
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype

# 分析
analytics:
  google_analytics:
    tracking_id: 
    localhost_ignored: true
  baidu_site_id:
  cnzz_site_id:
  tencent_site_id: